src/protected/models/TopicForm.php
<?php

class TopicForm extends CFormModel {
	
	public $title;
	public $body;
	
	/*public function rules() {
		return array(
			array('title, body', 'required'),
			);
	}*/
	
	public function attributeLabels() {
		return array(
			'title' => 'Title',
			'body' => 'Body',
			);
	}
	
}

?>

src/protected/controllers/PostController.php
<?php

class PostController extends Controller
{
	const PAGE_SIZE=10;

	/**
	 * @var string specifies the default action to be 'list'.
	 */
	public $defaultAction='list';

	/**
	 * Specifies the action filters.
	 * This method overrides the parent implementation.
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method overrides the parent implementation.
	 * It is only effective when 'accessControl' filter is enabled.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('deny',  // deny access to create, update, delete operations for guest users
				'actions'=>array('create','update','delete'),
				'users'=>array('?'),
			),
			array('allow', // allow access to admin operation for admin user
				'actions'=>array('admin'),
				'users'=>array('admin'),
			),
			array('deny',  // deny access to admin operation for all users
				'actions'=>array('admin'),
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Shows a particular posts.
	 */
	public function actionView()
	{
		$this->render('view',array('posts'=>$this->loadPosts()));
	}

	/**
	 * Creates a new posts.
	 * If creation is successful, the browser will be redirected to the 'show' page.
	 */
	public function actionCreate() {
		
		if(isset($_POST['Post'])) {
			
			$user = User::model()->find('username = :username', array('username' => Yii::app()->user->name));
			$session = Yii::app()->session;

			$topic = Topic::model()->findByPk($session['topic_id']);
			$forum = Forum::model()->findByPk($session['forum_id']);
			
			/*$transaction = Post::model()->dbConnection->beginTransaction();
			try {
			*/
				
				$now = date('Y-m-d H:i:s');
				
				$post = new Post();
				$post->user_id = $user->id;
				$post->topic_id = $session['topic_id'];
				$post->forum_id = $session['forum_id'];
				$post->body = $_POST['Post']['body'];
				// TODO: fix me
				$post->body_html = $post->body;				
				$post->created_at = $now;
				$post->updated_at = $now;
				
				if(!$post->save()) {
					var_dump('<pre>', $post->getErrors());
				}
				
				if(!$user->save()) {
					var_dump('<pre>', $user->getErrors());
				}

				$topic->updated_at = $now;
				/*$topic->replied_at = $now;
				$topic->replied_by = $user->id;
				$topic->last_post_id = $post->id;*/
				if(!$topic->save()) {
					var_dump('<pre>', $topic->getErrors());
				}

				/*$transaction->commit();

			} catch(Exception $e) {
				$transaction->rollBack();
				throw new CHttpException(500, 'Failed to save post');
			}*/
			
			$url = $this->createUrl('topic/view', array(
				'id' => $session['topic_id'], 
				'#' => "post-{$post->id}"
			));
			$this->redirect($url);
			
		}
		
	}

	/**
	 * Updates a particular posts.
	 * If update is successful, the browser will be redirected to the 'show' page.
	 */
	public function actionEdit()
	{
		$posts=$this->loadPosts();
		if(isset($_POST['Posts']))
		{
			$posts->setAttributes($_POST['Posts']);
			if($posts->save())
				$this->redirect(array('show','id'=>$posts->id));
		}
		$this->render('edit', array('posts'=>$posts));
	}

	/**
	 * Deletes a particular posts.
	 * If deletion is successful, the browser will be redirected to the 'list' page.
	 */
	public function actionDelete()
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadPosts()->delete();
			$this->redirect(array('list'));
		}
		else
			throw new CHttpException(500,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all postss.
	 */
	public function actionList()
	{
		$pages = $this->paginate(Post::model()->count(), self::PAGE_SIZE);
		$criteria = $this->getListCriteria($pages);
		$criteria->order = "t.created_at DESC";
		$postsList = Post::model()->with('author', 'forum', 'topic')->findAll($criteria);

		$this->render('list',array(
			'postsList'=>$postsList,
			'pages'=>$pages));
	}

	/**
	 * Manages all postss.
	 */
	public function actionAdmin()
	{
		$this->processAdminCommand();

		$pages=$this->paginate(Post::model()->count(), self::PAGE_SIZE);
		$postsList=Post::model()->findAll($this->getListCriteria($pages));

		$this->render('admin',array(
			'postsList'=>$postsList,
			'pages'=>$pages));
	}
	
	public function actionFeed() {
		
		Yii::import('application.lib.*');
		require_once('Zend/Feed.php');
		
		$posts = Post::model()->with('author')->findAll(array(
			'order' => 'post.created_at DESC',
			'limit' => 20,
			));
		//die(var_dump($posts));
		
		$data = array(
			'title' => Yii::app()->params['title']." Feed",
			'link' => Yii::app()->request->baseUrl,
			'charset' => 'utf-8',
			);
			
		foreach($posts as $post) {
			$entry = array(
				'title' => $post->body,
				'link' => CHtml::normalizeUrl(array('posts/show', 'id' => $post->id)),
				'description' => $post->body,
				'lastUpdate' => $post->created_at,
				);
			$data['entries'][] = $entry;
		}
		
		$feed = Zend_Feed::importArray($data);
		$feed->send();
	}

	/**
	 * Loads the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 */
	protected function loadPosts()
	{
		if(isset($_GET['id']))
			$posts=Post::model()->findbyPk($_GET['id']);
		if(isset($posts))
			return $posts;
		else
			throw new CHttpException(500,'The requested posts does not exist.');
	}

	/**
	 * @param CPagination the pagination information
	 * @return CDbCriteria the query criteria for Posts list.
	 * It includes the ORDER BY and LIMIT/OFFSET information.
	 */
	protected function getListCriteria($pages)
	{
		$criteria=new CDbCriteria;
		$columns=Post::model()->tableSchema->columns;
		if(isset($_GET['sort']) && isset($columns[$_GET['sort']]))
		{
			$criteria->order=$columns[$_GET['sort']]->rawName;
			if(isset($_GET['desc']))
				$criteria->order.=' DESC';
		}
		$criteria->limit=$pages->pageSize;
		$criteria->offset=$pages->currentPage*$pages->pageSize;
		return $criteria;
	}

	/**
	 * Generates the header cell for the specified column.
	 * This method will generate a hyperlink for the column.
	 * Clicking on the link will cause the data to be sorted according to the column.
	 * @param string the column name
	 * @return string the generated header cell content
	 */
	protected function generateColumnHeader($column)
	{
		$params=$_GET;
		if(isset($params['sort']) && $params['sort']===$column)
		{
			if(isset($params['desc']))
				unset($params['desc']);
			else
				$params['desc']=1;
		}
		else
		{
			$params['sort']=$column;
			unset($params['desc']);
		}
		$url=$this->createUrl('list',$params);
		return CHtml::link(Post::model()->getAttributeLabel($column),$url);
	}

	/**
	 * Executes any command triggered on the admin page.
	 */
	protected function processAdminCommand()
	{
		if(isset($_POST['command'], $_POST['id']) && $_POST['command']==='delete')
		{
			if(Yii::app()->user->isGuest)
				Yii::app()->user->loginRequired();

			if(($posts=Post::model()->findbyPk($_POST['id']))!==null)
			{
				$posts->delete();
				// reload the current page to avoid duplicated delete actions
				$this->refresh();
			}
			else
				throw new CHttpException(500,'The requested posts does not exist.');
		}
	}
}

src/protected/controllers/UserController.php
<?php

class UserController extends Controller {
	
	const PAGE_SIZE = 50;

	/**
	 * @var string specifies the default action to be 'list'.
	 */
	public $defaultAction='list';

	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xEBF4FB,
			),
		);
	}

	/**
	 * Specifies the action filters.
	 * This method overrides the parent implementation.
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method overrides the parent implementation.
	 * It is only effective when 'accessControl' filter is enabled.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('deny',  // deny access to create, update, delete operations for guest users
				'actions'=>array('update','delete'),
				'users'=>array('?'),
			),
			array('allow', // allow access to admin operation for admin user
				'actions'=>array('admin'),
				'users'=>array('admin'),
			),
			array('deny',  // deny access to admin operation for all users
				'actions'=>array('admin'),
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Shows a particular users.
	 */
	public function actionView() {
		$user = $this->loadUsers();
		//var_dump($user);
		$this->render('view', array('user' => $user));
	}

	/**
	 * Creates a new users.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate() {
		
		$form = new SignupForm();
		
		// collect user input data
		if(isset($_POST['SignupForm'])) {
			$form->attributes = $_POST['SignupForm'];
			//var_dump($_POST);
			//var_dump($form);
			
			// validate user input and redirect to previous page if valid
			if($form->validate()) {
				
				// TODO: validate passwords
				
				
				
				$user = new User();
				//$user->attributes = $_POST['SignupForm'];
				$user->username = $_POST['SignupForm']['username'];
				$user->email = $_POST['SignupForm']['email'];
				$user->password_hash = md5($_POST['SignupForm']['password']);
				$user->display_name = $_POST['SignupForm']['display_name'];
				$user->admin = 0;
				$user->posts_count = 0;
				$user->activated = 0;
				$user->login_key = md5($user->password_hash + $user->email);
				$user->login_key_expires_at = date('Y-m-d H:i:s', strtotime('+1 day'));
				
				
				//if(isset($_POST['Users'])) {
					/*$users->attributes = array(
						
						
					); ;*/
					//var_dump($users);
					
					//if($user->validate()) {
						
						if($user->save(false)) {
							
							$identity = new UserIdentity($user->username, $_POST['SignupForm']['password']);
							/*$identity->authenticate();
							switch($identity->errorCode)
							{
								case UserIdentity::ERROR_NONE:
									$duration=$this->rememberMe ? 3600*24*30 : 0; // 30 days
									Yii::app()->user->login($identity,$duration);
									break;
								case UserIdentity::ERROR_USERNAME_INVALID:
									$this->addError('username','Username is incorrect.');
									break;
								default: // UserIdentity::ERROR_PASSWORD_INVALID
									$this->addError('password','Password is incorrect.');
									break;
							}*/
							Yii::app()->user->login($identity);				
							$this->redirect(array('view', 'id' => $user->id));
							
						} else {
							var_dump($user->getErrors());
						}
						
					/*} else {
						var_dump($user->getErrors());
					}*/
					
					
				//}
				
				
				
				
				
				//var_dump($user);
				
				//$this->redirect(Yii::app()->user->returnUrl);
			}
		}
		// display the login form
		$this->render('create', array('form' => $form));
		
		/*$users=new User;
		if(isset($_POST['Users']))
		{
			$users->attributes=$_POST['Users'];
			if($users->save())
				$this->redirect(array('show','id'=>$users->id));
		}
		$this->render('create',array('users'=>$users));*/
	}

	/**
	 * Updates a particular users.
	 * If update is successful, the browser will be redirected to the 'show' page.
	 */
	public function actionEdit()
	{
		// if not admin, only update your own account information
		
		/*$form = new SignupForm();
		// collect user input data
		if(isset($_POST['SignupForm'])) {
			$form->attributes = $_POST['SignupForm'];
			// validate user input and redirect to previous page if valid
			if($form->validate()) {
		
		if($form->validate()) {*/
		
		$notice = "";
		
		$users = $this->loadUsers();
		if(isset($_POST['User'])) {
			
			/*if(isset($_POST['User']['display_name'])) {
				
				
				
			}
			
			
			var_dump($_POST);
			*/
			
			$users->setAttributes($_POST['User']);
			
			if($users->validate()) {
				if($users->save()) {
					$notice = "Your settings have been saved.";
					//$this->redirect(array('update', 'id' => $users->id));
				}
			} else {
				//var_dump($users->getErrors());
			}
			
			
			
		}
		
		$this->render('edit', array('users' => $users, 'notice' => $notice));
	}

	/**
	 * Deletes a particular users.
	 * If deletion is successful, the browser will be redirected to the 'list' page.
	 */
	public function actionDelete()
	{
		/*if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadUsers()->delete();
			$this->redirect(array('list'));
		}
		else
			throw new CHttpException(500,'Invalid request. Please do not repeat this request again.');*/
			
		throw new CHttpException(500,'No user should be deleted.');
	}

	/**
	 * Lists all userss.
	 */
	public function actionList()
	{
		$pages = $this->paginate(User::model()->count(), self::PAGE_SIZE);
		$criteria = $this->getListCriteria($pages);
		$criteria->order = "username";
		$usersList = User::model()->with('posts_count')->findAll($criteria);

		$this->render('list',array(
			'usersList'=>$usersList,
			'pages'=>$pages));
	}
	
	public function actionFeed() {
		
		//die(var_dump($_GET));
		
		
		
		Yii::import('application.vendors.*');
		require_once('Zend/Feed.php');
		
		$posts = Post::model()->with('author')->findAll(array(
			'where' => 'posts.user_id = :user_id',
			'order' => 'posts.created_at DESC',
			'limit' => 20,
			), array(
			':user_id' => 123123132,
			));
		//die(var_dump($posts));
		
		/*$data = array(
			'title' => Yii::app()->params['title']." Feed",
			'link' => Yii::app()->request->baseUrl,
			'charset' => 'utf-8',
			);
			
		foreach($posts as $post) {
			$entry = array(
				'title' => $post->body,
				'link' => CHtml::normalizeUrl(array('posts/show', 'id' => $post->id)),
				'description' => $post->body,
				'lastUpdate' => $post->created_at,
				);
			$data['entries'][] = $entry;
		}
		
		$feed = Zend_Feed::importArray($data);
		$feed->send();*/
		
	}

	/**
	 * Manages all userss.
	 */
	public function actionAdmin()
	{
		$this->processAdminCommand();

		$pages=$this->paginate(User::model()->count(), self::PAGE_SIZE);
		$usersList=User::model()->findAll($this->getListCriteria($pages));

		$this->render('admin',array(
			'usersList'=>$usersList,
			'pages'=>$pages));
	}

	/**
	 * Loads the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 */
	protected function loadUsers()
	{
		if(isset($_GET['id']))
			$users=User::model()->findbyPk($_GET['id']);
		if(isset($users))
			return $users;
		else
			throw new CHttpException(500,'The requested users does not exist.');
	}

	/**
	 * @param CPagination the pagination information
	 * @return CDbCriteria the query criteria for Users list.
	 * It includes the ORDER BY and LIMIT/OFFSET information.
	 */
	protected function getListCriteria($pages)
	{
		$criteria=new CDbCriteria;
		$columns=User::model()->tableSchema->columns;
		if(isset($_GET['sort']) && isset($columns[$_GET['sort']]))
		{
			$criteria->order=$columns[$_GET['sort']]->rawName;
			if(isset($_GET['desc']))
				$criteria->order.=' DESC';
		}
		$criteria->limit=$pages->pageSize;
		$criteria->offset=$pages->currentPage*$pages->pageSize;
		return $criteria;
	}

	/**
	 * Generates the header cell for the specified column.
	 * This method will generate a hyperlink for the column.
	 * Clicking on the link will cause the data to be sorted according to the column.
	 * @param string the column name
	 * @return string the generated header cell content
	 */
	protected function generateColumnHeader($column)
	{
		$params=$_GET;
		if(isset($params['sort']) && $params['sort']===$column)
		{
			if(isset($params['desc']))
				unset($params['desc']);
			else
				$params['desc']=1;
		}
		else
		{
			$params['sort']=$column;
			unset($params['desc']);
		}
		$url=$this->createUrl('list',$params);
		return CHtml::link(User::model()->getAttributeLabel($column),$url);
	}

	/**
	 * Executes any command triggered on the admin page.
	 */
	protected function processAdminCommand()
	{
		if(isset($_POST['command'], $_POST['id']) && $_POST['command']==='delete')
		{
			if(Yii::app()->user->isGuest)
				Yii::app()->user->loginRequired();

			if(($users=User::model()->findbyPk($_POST['id']))!==null)
			{
				$users->delete();
				// reload the current page to avoid duplicated delete actions
				$this->refresh();
			}
			else
				throw new CHttpException(500,'The requested users does not exist.');
		}
	}
}

src/protected/views/topic/admin.php
<h2>Managing Topics</h2>

<div class="actionBar">
[<?php echo CHtml::link('Topics List',array('list')); ?>]
[<?php echo CHtml::link('New Topics',array('create')); ?>]
</div>

<table class="dataGrid">
  <tr>
    <th><?php echo $this->generateColumnHeader('id'); ?></th>
    <th><?php echo $this->generateColumnHeader('forum_id'); ?></th>
    <th><?php echo $this->generateColumnHeader('user_id'); ?></th>
    <th><?php echo $this->generateColumnHeader('title'); ?></th>
    <th><?php echo $this->generateColumnHeader('created_at'); ?></th>
    <th><?php echo $this->generateColumnHeader('updated_at'); ?></th>
    <th><?php echo $this->generateColumnHeader('hits'); ?></th>
    <th><?php echo $this->generateColumnHeader('sticky'); ?></th>
    <th><?php echo $this->generateColumnHeader('posts_count'); ?></th>
    <th><?php echo $this->generateColumnHeader('replied_at'); ?></th>
    <th><?php echo $this->generateColumnHeader('locked'); ?></th>
    <th><?php echo $this->generateColumnHeader('replied_by'); ?></th>
    <th><?php echo $this->generateColumnHeader('last_post_id'); ?></th>
	<th>Actions</th>
  </tr>
<?php foreach($topicsList as $n=>$model): ?>
  <tr class="<?php echo $n%2?'even':'odd';?>">
    <td><?php echo CHtml::link($model->id,array('show','id'=>$model->id)); ?></td>
    <td><?php echo CHtml::encode($model->forum_id); ?></td>
    <td><?php echo CHtml::encode($model->user_id); ?></td>
    <td><?php echo CHtml::encode($model->title); ?></td>
    <td><?php echo CHtml::encode($model->created_at); ?></td>
    <td><?php echo CHtml::encode($model->updated_at); ?></td>
    <td><?php echo CHtml::encode($model->hits); ?></td>
    <td><?php echo CHtml::encode($model->sticky); ?></td>
    <td><?php echo CHtml::encode($model->posts_count); ?></td>
    <td><?php echo CHtml::encode($model->replied_at); ?></td>
    <td><?php echo CHtml::encode($model->locked); ?></td>
    <td><?php echo CHtml::encode($model->replied_by); ?></td>
    <td><?php echo CHtml::encode($model->last_post_id); ?></td>
    <td>
      <?php echo CHtml::link('Update',array('update','id'=>$model->id)); ?>
      <?php echo CHtml::linkButton('Delete',array(
      	  'submit'=>'',
      	  'params'=>array('command'=>'delete','id'=>$model->id),
      	  'confirm'=>"Are you sure to delete #{$model->id}?")); ?>
	</td>
  </tr>
<?php endforeach; ?>
</table>
<br/>
<?php $this->widget('CLinkPager',array('pages'=>$pages)); ?>

src/protected/views/topic/create.php
<div class="crumbs" xstyle="margin-top: 1.1em;">
	<?php echo CHtml::link('Forums', array('/')) ?> <span class="arrow">&rarr;</span>
	<?php echo CHtml::link($forum->name, array('forums/show', 'id' => $forum->id)) ?> <span class="arrow">&rarr;</span>
</div>

<h1>New Topic</h1>
<p class="subtitle">by <?php echo Yii::app()->user->name ?></p>

<!--<div class="actionBar">
[<?php echo CHtml::link('Topics List',array('list')); ?>]
[<?php echo CHtml::link('Manage Topics',array('admin')); ?>]
</div>-->

<?php echo CHtml::form(); ?>

<?php echo CHtml::errorSummary($form); ?>

<p>
	<?php echo CHtml::activeLabel($form, 'title'); ?><br/>
	<?php echo CHtml::activeTextField($form, 'title', array('size' => 30, 'tabindex' => 10, 'class' => 'primary')); ?>
</p>

<p>
	<?php echo CHtml::activeLabel($form, 'body'); ?><br/>
	<?php echo CHtml::activeTextArea($form, 'body', array('rows' => 12, 'cols' => 40, 'tabindex' => 20, 'id' => 'topic_body')); ?>
</p>

<div class="action">
<?php echo CHtml::submitButton('Post Topic'); ?><span class='button_or'>or <?php echo CHtml::link('Cancel', array('forums', 'id' => 1)) ?></span>
</div>

</form>

src/protected/views/topic/view.php
<div class="crumbs">
  <?php Yii::t('messages', 'This is a topic in') ?> <?php echo CHtml::link($topic->forum->name, array('forum/view', 'id' => $topic->forum->id)) ?>
</div>

<h1><?= $topic->title ?></h1>

<table border="0" cellspacing="0" cellpadding="0" class="posts wide">

<?php foreach($topic->posts as $post): ?>
<tr class="post hentry" id="post-<?php echo $post->id ?>-row">
	<td class="author vcard">
		<div class="date">
 			<a href="#post-<?php echo $post->id ?>" rel="bookmark" name="post-<?php echo $post->id ?>" id="post-<?php echo $post->id ?>">
				<abbr class="updated" title="<?php echo date_format(date_create($post->created_at), DateTime::ISO8601) ?>">
					<?php echo Yii::app()->dateFormatter->formatDateTime($post->created_at, 'medium', 'short') ?>
				</abbr>
			</a>
		</div>
		<img alt="Avatar" class="photo" height="32" src="http://www.gravatar.com/avatar/<?php echo md5($post->author->email) ?>.jpg&amp;rating=PG&amp;size=32" width="32" />
		<span class="fn"><?php echo CHtml::link($post->author->name, array('user/view', 'id' => $post->author->id)) ?></span>
		<span class="posts"><?php echo $post->author->postscounttext ?></span>
	</td>

	<td class="body entry-content" id="post-body-<?php echo $post->id ?>">
		
		<?= $post->getBodyHtml(); ?>

	</td>
</tr>

<tr class="spacer">
  <td colspan="2">
    <a name="posts-29247" id="posts-29247">&nbsp;</a>
  </td>
</tr>
<?php endforeach; ?>

<?php if(Yii::app()->user->isGuest): ?>
<tr>
	<td></td>
	<td class="reply">
		<p>
			<strong><?php echo CHtml::link(Yii::t('messages', 'Signup'), array('signup/'), array('class' => 'admin')) ?></strong> <?php echo Yii::t('messages', 'or') ?> 
			<strong><?php echo CHtml::link(Yii::t('messages', 'login'), array('login/'), array('class' => 'admin')) ?></strong> <?php echo Yii::t('messages', 'to post a reply') ?>.
		</p>
	</td>
</tr>

<?php else: ?>
	
<tr>
	<td valign="top"><strong><?php echo Yii::t('messages', 'Post your reply') ?></strong></td>
	<td>
		
		<?php echo CHtml::form(array('post/create')) ?>
			<textarea cols="100" id="post_body" name="Post[body]" rows="8"></textarea>
			<p>
			<input name="commit" type="submit" value="<?php echo Yii::t('messages', 'Save Reply') ?>" /> <input name="preview" type="submit" value="<?php echo Yii::t('messages', 'Preview') ?>" />
			</p>
		</form>
		
	</td>
</tr>

<!--	<div id="edit"></div>
	<tr>
		<td></td>
		<td class="reply">

			<a class="utility" href="#" onclick="ReplyForm.init(); return false;">Post your reply</a>

			<div id="reply" class="editbox">
				<div class="container">

					<?php echo CHtml::form(array('posts/create')) ?>
						
						<table width="100%" border="0" cellpadding="0" cellspacing="0">
							<tr>
								<td rowspan="2" width="70%">
									<textarea cols="40" id="post_body" name="Post[body]" rows="8"></textarea>
								</td>
								<td valign="top">
									<h5>Formatting Help</h5>

	                  <ul class="help">
	                    <li>*bold*
	                    &nbsp; &nbsp; &nbsp;
	                    _italics_
	                    &nbsp; &nbsp; &nbsp;<br />
	                    bq. <span>(quotes)</span></li>

	                    <li>"IBM":http://www.ibm.com</li>
	                    <li>* or # <span>(lists)</span></li>
	                  </ul>

	                </td>
	              </tr>
	              <tr>
	                <td valign="bottom" style="padding-bottom:15px;">

	                 <input name="commit" type="submit" value="Save Reply" /><span class="button_or">or <a href="#" onclick="$('reply').hide(); return false;">cancel</a></span>
	               </td>
	             </tr>
	          </table>
	        </form>      </div>
	    </div>
	    <script type="text/javascript">
	//<![CDATA[
	$('reply').hide();
	//]]>

	</script>

	  </td>
	</tr>-->

<?php endif; ?>

</table>