src/protected/models/User.php
<?php

class User extends CActiveRecord {
	
	/**
	 * Returns the static model of the specified AR class.
	 * This method is required by all child classes of CActiveRecord.
	 * @return CActiveRecord the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'user';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules() {
		return array(
			array('username','length','max'=>50),
			array('email','length','max'=>255),
			array('password_hash','length','max'=>32),
			array('display_name','length','max'=>100),
			array('login_key','length','max'=>32),
			array('website','length','max'=>255),
			array('openid_url','length','max'=>255),
			array('username, email, password_hash, created_at, admin, posts_count, last_seen_at, login_key, login_key_expires_at, activated', 'required'),
			array('id, admin, posts_count, activated', 'numerical', 'integerOnly'=>true),
		);
	}

	public function relations() {
		return array(
			'posts' => array(self::HAS_MANY, 'Post', 'user_id', 'order' => 'created_at DESC', 'limit' => 20),
			'posts_count' => array(self::STAT, 'Post', 'user_id'),
			'topics' => array(self::HAS_MANY, 'Topic', 'user_id', 'order' => 'created_at DESC', 'limit' => 20),
			'topics_count' => array(self::STAT, 'Topic', 'user_id'),
		);
	}

	public function getName() {
		if(!empty($this->display_name)) {
			return $this->display_name;
		} else {
			return $this->username;
		}
	}
	
	public function getPostsCountText() {
		if($this->posts_count == 0) {
			return "0 posts";
		}
		if($this->posts_count == 1) {
			return "1 post";
		}
		return $this->posts_count." posts";
	}
	
	public function getNiceCreatedAt() {
		return date('M j, Y g:ia');
	}

	protected function beforeSave() {
		if(parent::beforeSave()) {
			$now = date('Y-m-d H:i:s');
			if($this->isNewRecord) {
				$this->created_at = $now;
				$this->last_seen_at = $now;
				$this->last_login_at = $now;
			}
			$this->updated_at = $now;
			return true;
		}
		return false;
	}

	/*public function attributeLabels()
	{
		return array(
			'authorID'=>'Author',
		);
	}

	public function protectedAttributes()
	{
		return array();
	}*/
	
}

src/protected/controllers/TopicController.php
<?php

class TopicController extends Controller
{
	const PAGE_SIZE=10;

	/**
	 * @var string specifies the default action to be 'list'.
	 */
	public $defaultAction='list';

	/**
	 * Specifies the action filters.
	 * This method overrides the parent implementation.
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method overrides the parent implementation.
	 * It is only effective when 'accessControl' filter is enabled.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('deny',  // deny access to create, update, delete operations for guest users
				'actions'=>array('create','update','delete'),
				'users'=>array('?'),
			),
			array('allow', // allow access to admin operation for admin user
				'actions'=>array('admin'),
				'users'=>array('admin'),
			),
			array('deny',  // deny access to admin operation for all users
				'actions'=>array('admin'),
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Shows a particular topics.
	 */
	public function actionView() {
		//$topic = $this->loadTopic();

	//	var_dump($topic->forum_id);
	
		if(isset($_GET['id'])) {
			$topic = Topic::model()->with('forum', 'posts')->findByPk((int)$_GET['id']);
		}
		
		if($topic === null) {
			throw new CHttpException(500, 'The requested topic does not exist.');
		}
		
		//die(var_dump($topic->forum->name))
		
		// set current topic_id
		$session = Yii::app()->session;
		$session['topic_id'] = $topic->id;
		$session['forum_id'] = $topic->forum->id;
		
		// update hits
		// TODO: only if not already read it within the same session
		
		/*if(!isset($session['viewed_topics'])) {
			$session['viewed_topics'] = array();
		}*/
		
		
		if(isset($session['viewed_topics'][$topic->id])) {
			
			$topic->hits++;
			if(!$topic->save()) {
				var_dump($topic->getErrors());
			}
			
			$session['viewed_topics'][$topic->id] = true;
			
		}
		
		//die(var_dump(Yii::app()->session['topic_id'], $session['forum_id'], Yii::app()->session['viewed_topics']));

		$this->render('view', array('topic' => $topic));
	}

	/**
	 * Creates a new topic.
	 * If creation is successful, the browser will be redirected to the 'show' page.
	 */
	public function actionCreate() {
		
		// find forum
		if(isset($_GET['id'])) {
			$forum = Forum::model()->findByPk((int)$_GET['id']);
		}
		if(!isset($forum)) {
			throw new CHttpException(500, 'The requested forum does not exist.');
		}
		
		$form = new TopicForm();
		
		if(isset($_POST['TopicForm'])) {
			
			if($form->validate()) {
				
				
				
				//die(var_dump(Yii::app()->user->name));
				
				$user = User::model()->find('username = :username', array('username' => Yii::app()->user->name));
				if($user === null) {
					throw new Exception(500, 'You need to login to create a new topic');
				}
				
			
				
				/*$transaction = Topic::model()->dbConnection->beginTransaction();
				try {
				*/
					
					//die(var_dump($_POST['TopicForm']));
					
					$topic = new Topic();
					$topic->forum_id = $forum->id;
					$topic->user_id = $user->id;
					$topic->title = $_POST['TopicForm']['title'];
					$topic->hits = 1;
					$topic->sticky = 0;
					$topic->locked = 0;
					$topic->created_at = date('Y-m-d H:i:s');
					$topic->updated_at = date('Y-m-d H:i:s');					
					
					if(!$topic->save()) {
						die(var_dump('<pre>', $topic->getErrors()));
					}
					
					$post = new Post();
					$post->user_id = $user->id;
					$post->topic_id = $topic->id;
					$post->body = $_POST['TopicForm']['body'];
					// TODO: fix rendering?
					$post->body_html = $post->body;
					$post->created_at = date('Y-m-d H:i:s');
					$post->forum_id = $forum->id;
					
					if(!$post->save()) {
						var_dump('<pre>', $post->getErrors());
					}
					
					/*$user->posts_count++;
					if(!$user->save()) {
						var_dump('<pre>', $user->getErrors());
					}
					
					$forum->topics_count++;
					if(!$forum->save()) {
						var_dump('<pre>', $forum->getErrors());
					}*/
					
					//$transaction->commit();
					
				/*} catch(Exception $e) {
					$transaction->rollBack();
					throw new CHttpException(500, 'Failed to save topic');
				}*/
				
				$this->redirect(array('view', 'id' => $topic->id ));

			}
			
			/*if($user->save()) {
				//var_dump("user saved");
				
				//$this->redirect(array('show', 'id' => $users->id ));
				
			} else {
				var_dump($user->getErrors());
			}*/
			
		}
			
			
			//die(var_dump($_POST['TopicForm']));
			
			/*$topic = new Topic();
			if(isset($_POST['Topics']))
			{
				$topic->attributes=$_POST['Topics'];
				if($topic->save())
					$this->redirect(array('show','id'=>$topic->id));
			}*/
			
		$this->render('create', array('form' => $form, 'forum' => $forum));

	}

	/**
	 * Updates a particular topics.
	 * If update is successful, the browser will be redirected to the 'show' page.
	 */
	public function actionEdit()
	{
		$topics=$this->loadTopic();
		if(isset($_POST['Topics']))
		{
			$topics->setAttributes($_POST['Topics']);
			if($topics->save())
				$this->redirect(array('show','id'=>$topics->id));
		}
		$this->render('edit',array('topics'=>$topics));
	}

	/**
	 * Deletes a particular topics.
	 * If deletion is successful, the browser will be redirected to the 'list' page.
	 */
	public function actionDelete()
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadTopic()->delete();
			$this->redirect(array('list'));
		}
		else
			throw new CHttpException(500,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all topicss.
	 */
	public function actionList()
	{
		$pages=$this->paginate(Topics::model()->count(), self::PAGE_SIZE);
		$topicsList=Topics::model()->findAll($this->getListCriteria($pages));

		$this->render('list',array(
			'topicsList'=>$topicsList,
			'pages'=>$pages));
	}

	/**
	 * Manages all topicss.
	 */
	public function actionAdmin()
	{
		$this->processAdminCommand();

		$pages=$this->paginate(Topics::model()->count(), self::PAGE_SIZE);
		$topicsList=Topics::model()->findAll($this->getListCriteria($pages));

		$this->render('admin',array(
			'topicsList'=>$topicsList,
			'pages'=>$pages));
	}

	/**
	 * Loads the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 */
	protected function loadTopic()
	{
		if(isset($_GET['id'])) {
			$topic = Topic::model()->with('posts')->findbyPk($_GET['id']);
		}
		//die(var_dump($topic));
		if(isset($topic))
			return $topic;
		else
			throw new CHttpException(500,'The requested topic does not exist.');
	}
	
	protected function loadPosts() {
		if(isset($_GET['id'])) { // topic id is defined
			$posts = Post::model()->with('author')->findAll('topic_id = :topic_id', array(':topic_id' => $_GET['id']));			
		}
		if(isset($posts)) {
			return $posts;
		}
		// TODO
	}
	
	protected function loadForum() {
		/*if(isset($_GET['id'])) {
			$forum = Forum::model()->findAllBySql('SELECT * FROM forums WHERE ');
		}*/
		return array();
	}

	/**
	 * @param CPagination the pagination information
	 * @return CDbCriteria the query criteria for Topics list.
	 * It includes the ORDER BY and LIMIT/OFFSET information.
	 */
	protected function getListCriteria($pages)
	{
		$criteria=new CDbCriteria;
		$columns=Topics::model()->tableSchema->columns;
		if(isset($_GET['sort']) && isset($columns[$_GET['sort']]))
		{
			$criteria->order=$columns[$_GET['sort']]->rawName;
			if(isset($_GET['desc']))
				$criteria->order.=' DESC';
		}
		$criteria->limit=$pages->pageSize;
		$criteria->offset=$pages->currentPage*$pages->pageSize;
		return $criteria;
	}

	/**
	 * Generates the header cell for the specified column.
	 * This method will generate a hyperlink for the column.
	 * Clicking on the link will cause the data to be sorted according to the column.
	 * @param string the column name
	 * @return string the generated header cell content
	 */
	protected function generateColumnHeader($column)
	{
		$params=$_GET;
		if(isset($params['sort']) && $params['sort']===$column)
		{
			if(isset($params['desc']))
				unset($params['desc']);
			else
				$params['desc']=1;
		}
		else
		{
			$params['sort']=$column;
			unset($params['desc']);
		}
		$url=$this->createUrl('list',$params);
		return CHtml::link(Topics::model()->getAttributeLabel($column),$url);
	}

	/**
	 * Executes any command triggered on the admin page.
	 */
	protected function processAdminCommand()
	{
		if(isset($_POST['command'], $_POST['id']) && $_POST['command']==='delete')
		{
			if(Yii::app()->user->isGuest)
				Yii::app()->user->loginRequired();

			if(($topics=Topics::model()->findbyPk($_POST['id']))!==null)
			{
				$topics->delete();
				// reload the current page to avoid duplicated delete actions
				$this->refresh();
			}
			else
				throw new CHttpException(500,'The requested topics does not exist.');
		}
	}
}

src/protected/views/user/admin.php
<h2>Managing Users</h2>

<div class="actionBar">
[<?php echo CHtml::link('Users List',array('list')); ?>]
[<?php echo CHtml::link('New Users',array('create')); ?>]
</div>

<table class="dataGrid">
  <tr>
    <th><?php echo $this->generateColumnHeader('id'); ?></th>
    <th><?php echo $this->generateColumnHeader('login'); ?></th>
    <th><?php echo $this->generateColumnHeader('email'); ?></th>
    <th><?php echo $this->generateColumnHeader('password_hash'); ?></th>
    <th><?php echo $this->generateColumnHeader('created_at'); ?></th>
    <th><?php echo $this->generateColumnHeader('last_login_at'); ?></th>
    <th><?php echo $this->generateColumnHeader('admin'); ?></th>
    <th><?php echo $this->generateColumnHeader('posts_count'); ?></th>
    <th><?php echo $this->generateColumnHeader('last_seen_at'); ?></th>
    <th><?php echo $this->generateColumnHeader('display_name'); ?></th>
    <th><?php echo $this->generateColumnHeader('updated_at'); ?></th>
    <th><?php echo $this->generateColumnHeader('website'); ?></th>
    <th><?php echo $this->generateColumnHeader('login_key'); ?></th>
    <th><?php echo $this->generateColumnHeader('login_key_expires_at'); ?></th>
    <th><?php echo $this->generateColumnHeader('activated'); ?></th>
    <th><?php echo $this->generateColumnHeader('bio'); ?></th>
    <th><?php echo $this->generateColumnHeader('bio_html'); ?></th>
    <th><?php echo $this->generateColumnHeader('openid_url'); ?></th>
	<th>Actions</th>
  </tr>
<?php foreach($usersList as $n=>$model): ?>
  <tr class="<?php echo $n%2?'even':'odd';?>">
    <td><?php echo CHtml::link($model->id,array('show','id'=>$model->id)); ?></td>
    <td><?php echo CHtml::encode($model->login); ?></td>
    <td><?php echo CHtml::encode($model->email); ?></td>
    <td><?php echo CHtml::encode($model->password_hash); ?></td>
    <td><?php echo CHtml::encode($model->created_at); ?></td>
    <td><?php echo CHtml::encode($model->last_login_at); ?></td>
    <td><?php echo CHtml::encode($model->admin); ?></td>
    <td><?php echo CHtml::encode($model->posts_count); ?></td>
    <td><?php echo CHtml::encode($model->last_seen_at); ?></td>
    <td><?php echo CHtml::encode($model->display_name); ?></td>
    <td><?php echo CHtml::encode($model->updated_at); ?></td>
    <td><?php echo CHtml::encode($model->website); ?></td>
    <td><?php echo CHtml::encode($model->login_key); ?></td>
    <td><?php echo CHtml::encode($model->login_key_expires_at); ?></td>
    <td><?php echo CHtml::encode($model->activated); ?></td>
    <td><?php echo CHtml::encode($model->bio); ?></td>
    <td><?php echo CHtml::encode($model->bio_html); ?></td>
    <td><?php echo CHtml::encode($model->openid_url); ?></td>
    <td>
      <?php echo CHtml::link('Update',array('update','id'=>$model->id)); ?>
      <?php echo CHtml::linkButton('Delete',array(
      	  'submit'=>'',
      	  'params'=>array('command'=>'delete','id'=>$model->id),
      	  'confirm'=>"Are you sure to delete #{$model->id}?")); ?>
	</td>
  </tr>
<?php endforeach; ?>
</table>
<br/>
<?php $this->widget('CLinkPager',array('pages'=>$pages)); ?>

src/protected/views/user/create.php
<?php $this->pageTitle = Yii::t('messages', 'Sign up'); ?>

<h1><?php echo Yii::t('messages', 'Signup') ?></h1>

<?php echo CHtml::form() ?>

<?php echo CHtml::errorSummary($form) ?>

<p class="help"><?php echo Yii::t('messages', 'Logins should start with least 2 characters and may consist of letters, numbers, or the underscore.') ?></p>

<p>
<?php echo CHtml::activeLabel($form, 'username') ?><br/>
<?php echo CHtml::activeTextField($form, 'username', array('size' => 30)) ?>
</p>

<p>
<?php echo CHtml::activeLabel($form, 'email') ?><br/>
<?php echo CHtml::activeTextField($form, 'email', array('size' => 30)) ?>
</p>

<p>
<?php echo CHtml::activeLabel($form, 'display_name') ?><br/>
<?php echo CHtml::activeTextField($form, 'display_name', array('size' => 30)) ?>
</p>

<p>
<?php echo CHtml::activeLabel($form, 'password') ?><br/>
<?php echo CHtml::activePasswordField($form, 'password', array('size' => 30)) ?>
</p>

<p>
<?php echo CHtml::activeLabel($form, 'password_confirmation') ?><br/>
<?php echo CHtml::activePasswordField($form, 'password_confirmation', array('size' => 30)) ?>
</p>

<?php if(extension_loaded('gd')): ?>
<?php echo CHtml::activeLabel($form, 'verify_code'); ?>
	<div>
	<?php $this->widget('CCaptcha', array('buttonLabel' => Yii::t('messages', 'Get a new code'))); ?>
	<br/>
	<?php echo CHtml::activeTextField($form, 'verify_code'); ?>
	</div>
	<p class="entryhelp"><?php echo Yii::t('messages', 'Please enter the letters as they are shown in the image above.') ?>
	<br/><?php echo Yii::t('messages', 'Letters are not case-sensitive.') ?></p>
<?php endif; ?>

<?php echo CHtml::submitButton(Yii::t('messages', 'Sign up!')); ?>

</form>

src/protected/views/user/edit.php
<?php if($notice): ?>
<p class="notice"><?php echo $notice ?></p>
<?php endif; ?>

<h1>Settings</h1>
<h2>for <?php echo $users->display_name ?> (<?php echo $users->username ?>)</h2>

<?php echo CHtml::errorSummary($users); ?>

<h3>Basic</h3>

<?php echo CHtml::form(); ?>

<p>
<?php echo CHtml::activeLabel($users, 'email'); ?><br/>
<?php echo CHtml::activeTextField($users, 'email', array('size' => 30, 'maxlength' => 255)); ?>
</p>

<p>
<?php echo CHtml::activeLabel($users, 'password'); ?><br/>
<p class="entryhelp">Enter a new password twice to change your password. (must be longer than 5 characters)</p>
<?php echo CHtml::passwordField('password', '', array('size' => 16)); ?> <span class="entryhelp">(once)</span><br/>
<?php echo CHtml::passwordField('password_confirmation', '', array('size' => 16)); ?> <span class="entryhelp">(and again)</span>
</p>

<p>
<?php echo CHtml::submitButton('Change e-mail or password'); ?><span class="button_or">or <?php echo CHtml::link('cancel', array('list')); ?></span>
</p>

</form>

<h3>User Profile</h3>

<?php echo CHtml::form(); ?>

<p>
<?php echo CHtml::activeLabel($users, 'display_name'); ?><br/>
<?php echo CHtml::activeTextField($users, 'display_name', array('size' => 30)); ?>
</p>

<p>
<?php echo CHtml::activeLabel($users, 'openid_url'); ?><br/>
<p class="entryhelp">Enter your OpenID Identity Url if you know it.</p>
<?php echo CHtml::activeTextField($users, 'openid_url', array('size' => 30)); ?>
</p>

<p>
<?php echo CHtml::activeLabel($users, 'website'); ?><br/>
<?php echo CHtml::activeTextField($users, 'website', array('size' => 30)); ?> <span class="entryhelp">(without http://)</span>
</p>

<p>
<?php echo CHtml::activeLabel($users, 'bio'); ?><br/>
<?php echo CHtml::activeTextArea($users, 'bio', array('rows' => 10, 'cols' => 40, 'style' => 'width: 99%;')); ?>
</p>

<p>
<?php echo CHtml::submitButton('Update profile'); ?><span class="button_or">or <?php echo CHtml::link('cancel', array('list')); ?></span>
</p>

</form>

src/protected/views/user/list.php
<h1><?php echo Yii::t('messages', 'Users') ?></h1>

<?php $this->widget('CLinkPager', array('pages' => $pages)); ?>
<br/>
<br/>
<table border="0" cellspacing="0" cellpadding="0" class="wide forums">
	<tr>
		<th class="la" width="88%"><?php echo Yii::t('messages', 'Name') ?> / <?php echo Yii::t('messages', 'Login') ?></th>
		<th><?php echo Yii::t('messages', 'Website') ?></th>
		<th width="1%"><?php echo Yii::t('messages', 'Posts') ?></th>
	</tr>
	<?php foreach($usersList as $n => $user): ?>
	<tr>
		<td><?php echo CHtml::link($user->name, array('view', 'id' => $user->id)); ?></td>
		<td><?php echo CHtml::encode($user->website); ?></td>
		<td><?php echo CHtml::encode($user->posts_count); ?></td>
	</tr>
	<?php endforeach; ?>
</table>
<br/>
<?php $this->widget('CLinkPager',array('pages'=>$pages)); ?>

src/protected/views/user/view.php
<!--<div class="actions">
	<a href="#">Profile</a> | <a href="#">Settings</a>
</div>-->

<h1><?php echo $user->name ?></h1>

<p style="float: right;"><img alt="<?php echo $user->name ?>" class="photo" height="80" src="http://www.gravatar.com/avatar/<?php echo md5($user->email) ?>.jpg&amp;rating=PG&amp;size=80" width="80" /></p> 

<p class="subtitle">
  <a href="#"><img alt="Subscribe to <?php echo $user->name ?>" height="14" src="<?php echo Yii::app()->request->baseUrl; ?>/images/feed-icon.png?1217504846" width="14" /></a>
  <span>
	<?php echo $user->topics_count ?> <?php echo Yii::t('messages', '1#topic|n>1#topics', array($user->topics_count)); ?>,
	<?php echo $user->posts_count ?> <?php echo Yii::t('messages', '1#post|n>1#posts', array($user->posts_count)) ?>
    <!--
    (vis <a href="/users/506/posts">alle</a> | 
    <a href="/users/506/monitored">overvåket</a> innlegg)<br />
	-->
  </span>
</p>

<?php echo $user->bio_html ?>

<?php if($user->website): ?>
<p><strong><?php echo Yii::t('messages', 'Website') ?></strong> <?php echo CHtml::link($user->website, $user->website) ?>
<?php endif; ?>

<p><?php echo Yii::t('messages', 'Member since') ?> <?php echo Yii::app()->dateFormatter->formatDateTime($user->created_at, 'long', null) ?></p>

<?php if($user->topics): ?>
	<h2><?php echo Yii::t('messages', 'Latest topics') ?></h2>
	<p>
	<?php foreach($user->topics as $topic): ?>
		<?php echo Yii::app()->dateFormatter->formatDateTime($topic->created_at, 'long', null) ?> - <?php echo CHtml::link($topic->title, array('/topic/view', 'id' => $topic->id)) ?><br/>
	<?php endforeach; ?>
	</p>
<?php endif; ?>