src/protected/controllers/ForumController.php
<?php

class ForumController extends Controller
{
	const PAGE_SIZE = 10;

	/**
	 * @var string specifies the default action to be 'list'.
	 */
	public $defaultAction = 'list';

	/**
	 * Specifies the action filters.
	 * This method overrides the parent implementation.
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			//'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method overrides the parent implementation.
	 * It is only effective when 'accessControl' filter is enabled.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('deny',  // deny access to create, update, delete operations for guest users
				'actions'=>array('create','update','delete'),
				'users'=>array('?'),
			),
			array('allow', // allow access to admin operation for admin user
				'actions'=>array('admin'),
				'users'=>array('admin'),
			),
			/*array('deny',  // deny access to admin operation for all users
				'actions'=>array('admin'),
				'users'=>array('*'),
			),*/
		);
	}

	/**
	 * Shows a particular forum.
	 */
	public function actionView() {
		
		$forum = $this->loadforum();
		//var_dump($forum->topics[0]->last_post);
		
		$this->render('view', array('forum' => $forum));//, 'topics' => $this->loadtopics()));
	}

	/**
	 * Creates a new forum.
	 * If creation is successful, the browser will be redirected to the 'show' page.
	 */
	public function actionCreate()
	{
		$forum = new Forum();
		if(isset($_POST['Forum']))
		{
			$forum->attributes = $_POST['Forum'];
			if($forum->save())
				$this->redirect(array('show',' id' => $forum->id));
		}
		$this->render('create',array('forum' => $forum));
	}

	/**
	 * Updates a particular forum.
	 * If update is successful, the browser will be redirected to the 'show' page.
	 */
	public function actionUpdate()
	{
		$forum=$this->loadforum();
		if(isset($_POST['forum']))
		{
			$forum->setAttributes($_POST['forum']);
			if($forum->save())
				$this->redirect(array('show','id'=>$forum->id));
		}
		$this->render('update',array('forum'=>$forum));
	}

	/**
	 * Deletes a particular forum.
	 * If deletion is successful, the browser will be redirected to the 'list' page.
	 */
	public function actionDelete()
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadforum()->delete();
			$this->redirect(array('list'));
		}
		else
			throw new CHttpException(500,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all forums.
	 */
	public function actionList() {
		
		/*$forums = Forum::model()->with('topics_count')->findAll(array(
			'select' => 'id, name, description, posts_count',
			'order' => 'position',
			));*/
			
		$forums = Forum::model()->with('topics_count', 'posts_count', 'last_post')->findAll();
		
		//die(var_dump($forums[0]->last_post));
		
		//die(var_dump($forums[0]->topics_count, $forums[0]->posts_count));
		
		//Topic::model()->with('last_post');
		
		/*foreach($forums as $forum) {
			$topics = Topic::model()->with('last_post')->findBySql('SELECT * FROM topics WHERE forum_id = :forum_id ORDER BY replied_at DESC LIMIT 1', array(':forum_id' => $forum->id));
			var_dump($topics);
		}*/
		
		//die(var_dump($forums[2]->last_post));
		
		
		
		// SELECT replied_at, replied_by, last_post_id FROM topics WHERE forum_id = 1 ORDER BY replied_at DESC LIMIT 1;
				
		//var_dump($forums[2]->topics[0]->attributes);
		
		/*$last_posts = Post::model()->findAll(array(
			
			));
		
		SELECT *
		FROM posts
		GROUP BY topic_id
		ORDER BY updated_at
		LIMIT 0 , 30*/
		
		
		/*$this->render('list', array(
			'forums' => $forums,
			//'last_posts' => $last_posts
		));*/
		
		$pages = $this->paginate(forum::model()->count(), self::PAGE_SIZE);
		//$forumList = Forum::model()->findAll($this->getListCriteria($pages));
		$this->render('list', array('forums'=>$forums, 'pages'=>$pages));
	}

	/**
	 * Manages all forums.
	 */
	public function actionAdmin()
	{
		$this->processAdminCommand();

		$pages=$this->paginate(forum::model()->count(), self::PAGE_SIZE);
		$forumList=forum::model()->findAll($this->getListCriteria($pages));

		$this->render('admin',array(
			'forumList'=>$forumList,
			'pages'=>$pages));
	}

	/**
	 * Loads the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 */
	protected function loadforum()
	{
		if(isset($_GET['id'])) {
			$forum = Forum::model()->with('topics')->findbyPk($_GET['id']);
		}
			
		if(isset($forum))
			return $forum;
		else
			throw new CHttpException(500,'The requested forum does not exist.');
	}

	protected function loadtopics() {
		if(isset($_GET['id'])) {
			$topics = Topic::model()->with('author')->findAll('forum_id = :forum_id', array(':forum_id' => $_GET['id']));
			//$topics = Topic::model()->findAllBySql('SELECT * FROM topics WHERE forum_id = :forum_id', array(':forum_id' => (int)$_GET['id']));
		}
		return $topics;
	}

	/**
	 * @param CPagination the pagination information
	 * @return CDbCriteria the query criteria for forum list.
	 * It includes the ORDER BY and LIMIT/OFFSET information.
	 */
	protected function getListCriteria($pages)
	{
		$criteria=new CDbCriteria;
		$columns=forum::model()->tableSchema->columns;
		if(isset($_GET['sort']) && isset($columns[$_GET['sort']]))
		{
			$criteria->order=$columns[$_GET['sort']]->rawName;
			if(isset($_GET['desc']))
				$criteria->order.=' DESC';
		}
		$criteria->limit=$pages->pageSize;
		$criteria->offset=$pages->currentPage*$pages->pageSize;
		return $criteria;
	}

	/**
	 * Generates the header cell for the specified column.
	 * This method will generate a hyperlink for the column.
	 * Clicking on the link will cause the data to be sorted according to the column.
	 * @param string the column name
	 * @return string the generated header cell content
	 */
	protected function generateColumnHeader($column)
	{
		$params=$_GET;
		if(isset($params['sort']) && $params['sort']===$column)
		{
			if(isset($params['desc']))
				unset($params['desc']);
			else
				$params['desc']=1;
		}
		else
		{
			$params['sort']=$column;
			unset($params['desc']);
		}
		$url=$this->createUrl('list',$params);
		return CHtml::link(forum::model()->getAttributeLabel($column),$url);
	}

	/**
	 * Executes any command triggered on the admin page.
	 */
	protected function processAdminCommand()
	{
		if(isset($_POST['command'], $_POST['id']) && $_POST['command']==='delete')
		{
			if(Yii::app()->user->isGuest)
				Yii::app()->user->loginRequired();

			if(($forum=forum::model()->findbyPk($_POST['id']))!==null)
			{
				$forum->delete();
				// reload the current page to avoid duplicated delete actions
				$this->refresh();
			}
			else
				throw new CHttpException(500,'The requested forum does not exist.');
		}
	}
}

src/protected/controllers/UserController.php
<?php

class UserController extends Controller {
	
	const PAGE_SIZE = 50;

	/**
	 * @var string specifies the default action to be 'list'.
	 */
	public $defaultAction='list';

	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xEBF4FB,
			),
		);
	}

	/**
	 * Specifies the action filters.
	 * This method overrides the parent implementation.
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method overrides the parent implementation.
	 * It is only effective when 'accessControl' filter is enabled.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('deny',  // deny access to create, update, delete operations for guest users
				'actions'=>array('update','delete'),
				'users'=>array('?'),
			),
			array('allow', // allow access to admin operation for admin user
				'actions'=>array('admin'),
				'users'=>array('admin'),
			),
			array('deny',  // deny access to admin operation for all users
				'actions'=>array('admin'),
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Shows a particular users.
	 */
	public function actionView() {
		$user = $this->loadUsers();
		//var_dump($user);
		$this->render('view', array('user' => $user));
	}

	/**
	 * Creates a new users.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate() {
		
		$form = new SignupForm();
		
		// collect user input data
		if(isset($_POST['SignupForm'])) {
			$form->attributes = $_POST['SignupForm'];
			//var_dump($_POST);
			//var_dump($form);
			
			// validate user input and redirect to previous page if valid
			if($form->validate()) {
				
				// TODO: validate passwords
				
				
				
				$user = new User();
				//$user->attributes = $_POST['SignupForm'];
				$user->username = $_POST['SignupForm']['username'];
				$user->email = $_POST['SignupForm']['email'];
				$user->password_hash = md5($_POST['SignupForm']['password']);
				$user->display_name = $_POST['SignupForm']['display_name'];
				$user->admin = 0;
				$user->posts_count = 0;
				$user->activated = 0;
				$user->login_key = md5($user->password_hash + $user->email);
				$user->login_key_expires_at = date('Y-m-d H:i:s', strtotime('+1 day'));
				
				
				//if(isset($_POST['Users'])) {
					/*$users->attributes = array(
						
						
					); ;*/
					//var_dump($users);
					
					//if($user->validate()) {
						
						if($user->save(false)) {
							
							$identity = new UserIdentity($user->username, $_POST['SignupForm']['password']);
							/*$identity->authenticate();
							switch($identity->errorCode)
							{
								case UserIdentity::ERROR_NONE:
									$duration=$this->rememberMe ? 3600*24*30 : 0; // 30 days
									Yii::app()->user->login($identity,$duration);
									break;
								case UserIdentity::ERROR_USERNAME_INVALID:
									$this->addError('username','Username is incorrect.');
									break;
								default: // UserIdentity::ERROR_PASSWORD_INVALID
									$this->addError('password','Password is incorrect.');
									break;
							}*/
							Yii::app()->user->login($identity);				
							$this->redirect(array('view', 'id' => $user->id));
							
						} else {
							var_dump($user->getErrors());
						}
						
					/*} else {
						var_dump($user->getErrors());
					}*/
					
					
				//}
				
				
				
				
				
				//var_dump($user);
				
				//$this->redirect(Yii::app()->user->returnUrl);
			}
		}
		// display the login form
		$this->render('create', array('form' => $form));
		
		/*$users=new User;
		if(isset($_POST['Users']))
		{
			$users->attributes=$_POST['Users'];
			if($users->save())
				$this->redirect(array('show','id'=>$users->id));
		}
		$this->render('create',array('users'=>$users));*/
	}

	/**
	 * Updates a particular users.
	 * If update is successful, the browser will be redirected to the 'show' page.
	 */
	public function actionEdit()
	{
		// if not admin, only update your own account information
		
		/*$form = new SignupForm();
		// collect user input data
		if(isset($_POST['SignupForm'])) {
			$form->attributes = $_POST['SignupForm'];
			// validate user input and redirect to previous page if valid
			if($form->validate()) {
		
		if($form->validate()) {*/
		
		$notice = "";
		
		$users = $this->loadUsers();
		if(isset($_POST['User'])) {
			
			/*if(isset($_POST['User']['display_name'])) {
				
				
				
			}
			
			
			var_dump($_POST);
			*/
			
			$users->setAttributes($_POST['User']);
			
			if($users->validate()) {
				if($users->save()) {
					$notice = "Your settings have been saved.";
					//$this->redirect(array('update', 'id' => $users->id));
				}
			} else {
				//var_dump($users->getErrors());
			}
			
			
			
		}
		
		$this->render('edit', array('users' => $users, 'notice' => $notice));
	}

	/**
	 * Deletes a particular users.
	 * If deletion is successful, the browser will be redirected to the 'list' page.
	 */
	public function actionDelete()
	{
		/*if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadUsers()->delete();
			$this->redirect(array('list'));
		}
		else
			throw new CHttpException(500,'Invalid request. Please do not repeat this request again.');*/
			
		throw new CHttpException(500,'No user should be deleted.');
	}

	/**
	 * Lists all userss.
	 */
	public function actionList()
	{
		$pages = $this->paginate(User::model()->count(), self::PAGE_SIZE);
		$criteria = $this->getListCriteria($pages);
		$criteria->order = "username";
		$usersList = User::model()->with('posts_count')->findAll($criteria);

		$this->render('list',array(
			'usersList'=>$usersList,
			'pages'=>$pages));
	}
	
	public function actionFeed() {
		
		//die(var_dump($_GET));
		
		
		
		Yii::import('application.vendors.*');
		require_once('Zend/Feed.php');
		
		$posts = Post::model()->with('author')->findAll(array(
			'where' => 'posts.user_id = :user_id',
			'order' => 'posts.created_at DESC',
			'limit' => 20,
			), array(
			':user_id' => 123123132,
			));
		//die(var_dump($posts));
		
		/*$data = array(
			'title' => Yii::app()->params['title']." Feed",
			'link' => Yii::app()->request->baseUrl,
			'charset' => 'utf-8',
			);
			
		foreach($posts as $post) {
			$entry = array(
				'title' => $post->body,
				'link' => CHtml::normalizeUrl(array('posts/show', 'id' => $post->id)),
				'description' => $post->body,
				'lastUpdate' => $post->created_at,
				);
			$data['entries'][] = $entry;
		}
		
		$feed = Zend_Feed::importArray($data);
		$feed->send();*/
		
	}

	/**
	 * Manages all userss.
	 */
	public function actionAdmin()
	{
		$this->processAdminCommand();

		$pages=$this->paginate(User::model()->count(), self::PAGE_SIZE);
		$usersList=User::model()->findAll($this->getListCriteria($pages));

		$this->render('admin',array(
			'usersList'=>$usersList,
			'pages'=>$pages));
	}

	/**
	 * Loads the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 */
	protected function loadUsers()
	{
		if(isset($_GET['id']))
			$users=User::model()->findbyPk($_GET['id']);
		if(isset($users))
			return $users;
		else
			throw new CHttpException(500,'The requested users does not exist.');
	}

	/**
	 * @param CPagination the pagination information
	 * @return CDbCriteria the query criteria for Users list.
	 * It includes the ORDER BY and LIMIT/OFFSET information.
	 */
	protected function getListCriteria($pages)
	{
		$criteria=new CDbCriteria;
		$columns=User::model()->tableSchema->columns;
		if(isset($_GET['sort']) && isset($columns[$_GET['sort']]))
		{
			$criteria->order=$columns[$_GET['sort']]->rawName;
			if(isset($_GET['desc']))
				$criteria->order.=' DESC';
		}
		$criteria->limit=$pages->pageSize;
		$criteria->offset=$pages->currentPage*$pages->pageSize;
		return $criteria;
	}

	/**
	 * Generates the header cell for the specified column.
	 * This method will generate a hyperlink for the column.
	 * Clicking on the link will cause the data to be sorted according to the column.
	 * @param string the column name
	 * @return string the generated header cell content
	 */
	protected function generateColumnHeader($column)
	{
		$params=$_GET;
		if(isset($params['sort']) && $params['sort']===$column)
		{
			if(isset($params['desc']))
				unset($params['desc']);
			else
				$params['desc']=1;
		}
		else
		{
			$params['sort']=$column;
			unset($params['desc']);
		}
		$url=$this->createUrl('list',$params);
		return CHtml::link(User::model()->getAttributeLabel($column),$url);
	}

	/**
	 * Executes any command triggered on the admin page.
	 */
	protected function processAdminCommand()
	{
		if(isset($_POST['command'], $_POST['id']) && $_POST['command']==='delete')
		{
			if(Yii::app()->user->isGuest)
				Yii::app()->user->loginRequired();

			if(($users=User::model()->findbyPk($_POST['id']))!==null)
			{
				$users->delete();
				// reload the current page to avoid duplicated delete actions
				$this->refresh();
			}
			else
				throw new CHttpException(500,'The requested users does not exist.');
		}
	}
}

src/protected/views/post/admin.php
<h2>Managing Posts</h2>

<div class="actionBar">
[<?php echo CHtml::link('Posts List',array('list')); ?>]
[<?php echo CHtml::link('New Posts',array('create')); ?>]
</div>

<table class="dataGrid">
  <tr>
    <th><?php echo $this->generateColumnHeader('id'); ?></th>
    <th><?php echo $this->generateColumnHeader('user_id'); ?></th>
    <th><?php echo $this->generateColumnHeader('topic_id'); ?></th>
    <th><?php echo $this->generateColumnHeader('body'); ?></th>
    <th><?php echo $this->generateColumnHeader('created_at'); ?></th>
    <th><?php echo $this->generateColumnHeader('updated_at'); ?></th>
    <th><?php echo $this->generateColumnHeader('forum_id'); ?></th>
    <th><?php echo $this->generateColumnHeader('body_html'); ?></th>
	<th>Actions</th>
  </tr>
<?php foreach($postsList as $n=>$model): ?>
  <tr class="<?php echo $n%2?'even':'odd';?>">
    <td><?php echo CHtml::link($model->id,array('show','id'=>$model->id)); ?></td>
    <td><?php echo CHtml::encode($model->user_id); ?></td>
    <td><?php echo CHtml::encode($model->topic_id); ?></td>
    <td><?php echo CHtml::encode($model->body); ?></td>
    <td><?php echo CHtml::encode($model->created_at); ?></td>
    <td><?php echo CHtml::encode($model->updated_at); ?></td>
    <td><?php echo CHtml::encode($model->forum_id); ?></td>
    <td><?php echo CHtml::encode($model->body_html); ?></td>
    <td>
      <?php echo CHtml::link('Update',array('update','id'=>$model->id)); ?>
      <?php echo CHtml::linkButton('Delete',array(
      	  'submit'=>'',
      	  'params'=>array('command'=>'delete','id'=>$model->id),
      	  'confirm'=>"Are you sure to delete #{$model->id}?")); ?>
	</td>
  </tr>
<?php endforeach; ?>
</table>
<br/>
<?php $this->widget('CLinkPager',array('pages'=>$pages)); ?>

src/protected/views/post/create.php
<h2>New Posts</h2>

<div class="actionBar">
[<?php echo CHtml::link('Posts List',array('list')); ?>]
[<?php echo CHtml::link('Manage Posts',array('admin')); ?>]
</div>

<div class="yiiForm">
<?php echo CHtml::form(); ?>

<?php echo CHtml::errorSummary($posts); ?>

<div class="simple">
<?php echo CHtml::activeLabel($posts,'user_id'); ?>
<?php echo CHtml::activeTextField($posts,'user_id'); ?>
</div>
<div class="simple">
<?php echo CHtml::activeLabel($posts,'topic_id'); ?>
<?php echo CHtml::activeTextField($posts,'topic_id'); ?>
</div>
<div class="simple">
<?php echo CHtml::activeLabel($posts,'body'); ?>
<?php echo CHtml::activeTextArea($posts,'body',array('rows'=>6, 'cols'=>50)); ?>
</div>
<div class="simple">
<?php echo CHtml::activeLabel($posts,'created_at'); ?>
<?php echo CHtml::activeTextField($posts,'created_at'); ?>
</div>
<div class="simple">
<?php echo CHtml::activeLabel($posts,'updated_at'); ?>
<?php echo CHtml::activeTextField($posts,'updated_at'); ?>
</div>
<div class="simple">
<?php echo CHtml::activeLabel($posts,'forum_id'); ?>
<?php echo CHtml::activeTextField($posts,'forum_id'); ?>
</div>
<div class="simple">
<?php echo CHtml::activeLabel($posts,'body_html'); ?>
<?php echo CHtml::activeTextArea($posts,'body_html',array('rows'=>6, 'cols'=>50)); ?>
</div>

<div class="action">
<?php echo CHtml::submitButton('Create'); ?>
</div>

</form>
</div><!-- yiiForm -->

src/protected/views/post/edit.php
<h2>Update Posts <?php echo $posts->id; ?></h2>

<div class="actionBar">
[<?php echo CHtml::link('Posts List',array('list')); ?>]
[<?php echo CHtml::link('New Posts',array('create')); ?>]
[<?php echo CHtml::link('Manage Posts',array('admin')); ?>]
</div>

<div class="yiiForm">
<?php echo CHtml::form(); ?>

<?php echo CHtml::errorSummary($posts); ?>

<div class="simple">
<?php echo CHtml::activeLabel($posts,'user_id'); ?>
<?php echo CHtml::activeTextField($posts,'user_id'); ?>
</div>
<div class="simple">
<?php echo CHtml::activeLabel($posts,'topic_id'); ?>
<?php echo CHtml::activeTextField($posts,'topic_id'); ?>
</div>
<div class="simple">
<?php echo CHtml::activeLabel($posts,'body'); ?>
<?php echo CHtml::activeTextArea($posts,'body',array('rows'=>6, 'cols'=>50)); ?>
</div>
<div class="simple">
<?php echo CHtml::activeLabel($posts,'created_at'); ?>
<?php echo CHtml::activeTextField($posts,'created_at'); ?>
</div>
<div class="simple">
<?php echo CHtml::activeLabel($posts,'updated_at'); ?>
<?php echo CHtml::activeTextField($posts,'updated_at'); ?>
</div>
<div class="simple">
<?php echo CHtml::activeLabel($posts,'forum_id'); ?>
<?php echo CHtml::activeTextField($posts,'forum_id'); ?>
</div>
<div class="simple">
<?php echo CHtml::activeLabel($posts,'body_html'); ?>
<?php echo CHtml::activeTextArea($posts,'body_html',array('rows'=>6, 'cols'=>50)); ?>
</div>

<div class="action">
<?php echo CHtml::submitButton('Save'); ?>
</div>

</form>
</div><!-- yiiForm -->

src/protected/views/post/list.php
<h1><?php echo Yii::t('messages', 'Recent Posts') ?></h1>

<?php $this->widget('CLinkPager', array(
	'pages' => $pages,
	'header' => Yii::t('messages', 'Go to page:'),
	'prevPageLabel' => Yii::t('messages', '< Previous'),
	'nextPageLabel' => Yii::t('messages', 'Next >'),
)); ?>
<br/>
<br/>
<table border="0" cellspacing="0" cellpadding="0" class="posts wide">
<?php foreach($postsList as $post): ?>
	<tr class="post hentry" id="posts-<?php echo $post->id ?>">
	  <td class="author vcard">
	    <div class="date">
	      <abbr class="updated" title="<?php echo date_format(date_create($post->created_at), DateTime::ISO8601) ?>">
	      	<?php echo Yii::app()->dateFormatter->formatDateTime($post->created_at, 'medium', 'short') ?>
	      </abbr>
	    </div>
	    <img alt="<?php echo $post->author->name ?>" class="photo" height="32" src="http://www.gravatar.com/avatar/<?php echo md5($post->author->email) ?>.jpg&amp;rating=PG&amp;size=32" width="32" />
	    <span class="fn"><?php echo CHtml::link($post->author->name, array('user/view', 'id' => $post->author->id)) ?></span>
	    <span class="posts"><?php echo $post->author->posts_count; ?> <?php echo Yii::t('messages', '1#post|n>1#posts', array($post->author->posts_count)); ?></span>
	  </td>
	  <td class="body entry-content">
	    <p class="topic">
	      <?php echo Yii::t('messages', 'Topic') ?>: <?php echo CHtml::link($post->forum->name, array('forum/view', 'id' => $post->forum->id)) ?> / 
			<?php echo CHtml::link($post->topic->title, array('topic/view', 'id' => $post->topic->id)) ?>
	    </p>
		<?php echo $post->getBodyHtml() ?>
	  </td>
	</tr>
	
	<tr class="spacer">
	  <td colspan="2">&nbsp;</td>
	</tr>

<?php endforeach; ?>
</table>
<br/>
<?php $this->widget('CLinkPager', array(
	'pages' => $pages,
	'header' => Yii::t('messages', 'Go to page:'),
	'prevPageLabel' => Yii::t('messages', '< Previous'),
	'nextPageLabel' => Yii::t('messages', 'Next >'),
)); ?>

src/protected/views/post/view.php
<h2>View Posts <?php echo $posts->id; ?></h2>

<div class="actionBar">
[<?php echo CHtml::link('Posts List',array('list')); ?>]
[<?php echo CHtml::link('New Posts',array('create')); ?>]
[<?php echo CHtml::link('Update Posts',array('edit','id'=>$posts->id)); ?>]
[<?php echo CHtml::linkButton('Delete Posts',array('submit'=>array('delete','id'=>$posts->id),'confirm'=>'Are you sure?')); ?>
]
[<?php echo CHtml::link('Manage Posts',array('admin')); ?>]
</div>

<table class="dataGrid">
<tr>
	<th class="label"><?php echo CHtml::encode($posts->getAttributeLabel('user_id')); ?>
</th>
    <td><?php echo CHtml::encode($posts->user_id); ?>
</td>
</tr>
<tr>
	<th class="label"><?php echo CHtml::encode($posts->getAttributeLabel('topic_id')); ?>
</th>
    <td><?php echo CHtml::encode($posts->topic_id); ?>
</td>
</tr>
<tr>
	<th class="label"><?php echo CHtml::encode($posts->getAttributeLabel('body')); ?>
</th>
    <td><?php echo CHtml::encode($posts->body); ?>
</td>
</tr>
<tr>
	<th class="label"><?php echo CHtml::encode($posts->getAttributeLabel('created_at')); ?>
</th>
    <td><?php echo CHtml::encode($posts->created_at); ?>
</td>
</tr>
<tr>
	<th class="label"><?php echo CHtml::encode($posts->getAttributeLabel('updated_at')); ?>
</th>
    <td><?php echo CHtml::encode($posts->updated_at); ?>
</td>
</tr>
<tr>
	<th class="label"><?php echo CHtml::encode($posts->getAttributeLabel('forum_id')); ?>
</th>
    <td><?php echo CHtml::encode($posts->forum_id); ?>
</td>
</tr>
<tr>
	<th class="label"><?php echo CHtml::encode($posts->getAttributeLabel('body_html')); ?>
</th>
    <td><?php echo CHtml::encode($posts->body_html); ?>
</td>
</tr>
</table>